FROM node:18.12 as builder
WORKDIR /app
COPY package.json ./
RUN npm install --ignore-scripts
COPY . ./
RUN ls -la
RUN npm run build:local
RUN ls -la /app/dist

# nginx part
FROM nginx:alpine
COPY ./nginx.conf /etc/nginx/nginx.conf
## Remove default nginx index page
RUN rm -rf /usr/share/nginx/html/*
# Copy from the stahg 1
COPY --from=builder /app/build /usr/share/nginx/html
EXPOSE 4173
# run nginx with global directives and daemon off
ENTRYPOINT ["nginx", "-g", "daemon off;"]